import { useMemo, useState, type FormEvent } from "react";
import { CircleHelp, Gauge, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { useLocalProject, type LocalMachineCondition } from "@/localStore";
import { getMachineDailyStatus } from "@/machines";
const Kicker=({children}:{children:React.ReactNode})=><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#71756f]">{children}</p>;
const today=()=>new Date().toISOString().slice(0,10);
const style:Record<string,string>={Trabalhando:"bg-[#e5efd0] text-[#617a31]",Parado:"bg-[#f1dfc5] text-[#a56c1e]",Manutenção:"bg-[#f4d7d3] text-[#b84f42]",Disponível:"bg-[#e4e8ed] text-[#52626f]","Sem lançamento":"bg-[#dedfda] text-[#626760]"};
export default function MachinesPage(){const {project,addMachine,upsertMachineLog}=useLocalProject();const [showNew,setShowNew]=useState(false);const [showLog,setShowLog]=useState(false);const [date,setDate]=useState(today);const [name,setName]=useState("");const [type,setType]=useState("");const [identifier,setIdentifier]=useState("");const [machineId,setMachineId]=useState("");const [frontId,setFrontId]=useState("");const [operator,setOperator]=useState("");const [condition,setCondition]=useState<LocalMachineCondition>("Trabalhando");const [start,setStart]=useState("");const [end,setEnd]=useState("");const [note,setNote]=useState("");const daily=useMemo(()=>getMachineDailyStatus(project,date),[project,date]);
const saveMachine=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!name.trim()||!type.trim()||!identifier.trim()){toast.error("Informe nome, tipo e identificação.");return;}addMachine({name:name.trim(),type:type.trim(),identifier:identifier.trim(),active:true});setName("");setType("");setIdentifier("");setShowNew(false);toast.success("Máquina cadastrada");};
const saveLog=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!machineId){toast.error("Selecione uma máquina.");return;}if(condition==="Trabalhando"&&!frontId){toast.error("Selecione a frente.");return;}const s=start.trim()?Number(start):undefined;const f=end.trim()?Number(end):undefined;if((s!==undefined&&!Number.isFinite(s))||(f!==undefined&&!Number.isFinite(f))){toast.error("Horímetro inválido.");return;}if(condition==="Trabalhando"&&(s===undefined||f===undefined)){toast.error("Informe horímetro inicial e final.");return;}if(s!==undefined&&f!==undefined&&f<s){toast.error("Horímetro final menor que inicial.");return;}upsertMachineLog({date,machineId,frontId:condition==="Trabalhando"?frontId:undefined,operator:operator.trim()||"Não informado",condition,hourmeterStart:s,hourmeterEnd:f,note:note.trim()});setNote("");setShowLog(false);toast.success("Lançamento atualizado");};
return <div className="min-h-screen bg-[#ececea] px-4 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><header className="border-b border-black/10 pb-6"><Kicker>Controle de equipamentos</Kicker><h1 className="mt-3 text-5xl font-black uppercase tracking-[-0.08em]">Máquinas</h1><p className="mt-3 max-w-2xl text-sm text-[#70756e]">Consulte os equipamentos e seus lançamentos. O cadastro e o horímetro só aparecem quando você solicitar.</p></header><div className="mt-6 flex flex-wrap gap-3"><Button onClick={()=>setShowNew(true)} className="bg-[#202321] text-white"><Plus className="mr-2 h-4 w-4"/>Nova máquina</Button><Button onClick={()=>setShowLog(true)} variant="outline"><Gauge className="mr-2 h-4 w-4"/>Lançar horímetro</Button><Input type="date" value={date} onChange={e=>setDate(e.target.value)} className="ml-auto h-10 w-40 bg-white"/></div><section className="mt-7"><div className="mb-3"><Kicker>Quadro do dia</Kicker><h2 className="mt-1 text-2xl font-black uppercase">Equipamentos</h2></div><div className="space-y-3">{daily.map(({machine,log,condition:current,hours})=><Card key={machine.id} className="rounded-none border-0 bg-[#f6f6f3] shadow-[4px_4px_0_#d0d1cb]"><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><Kicker>{machine.identifier} · {machine.type}</Kicker><h3 className="mt-1 text-base font-black uppercase">{machine.name}</h3><p className="mt-2 text-xs text-[#70756e]">{log?.operator??"Sem operador"}{log?.frontId?` · ${project.fronts.find(f=>f.id===log.frontId)?.code??"—"}`:""}{log?.note?` · ${log.note}`:""}</p></div><div className="flex items-center gap-3"><span className={`px-2 py-1 text-[10px] font-bold uppercase ${style[current]}`}>{current}</span><strong>{hours.toFixed(1)} h</strong></div></CardContent></Card>)}{daily.length===0&&<Card className="rounded-none border-0 bg-[#f6f6f3]"><CardContent className="p-6"><CircleHelp className="h-5 w-5 text-[#789249]"/><p className="mt-2 text-sm text-[#70756e]">Nenhuma máquina cadastrada. Use “Nova máquina” para começar.</p></CardContent></Card>}</div></section>
{showNew&&<Modal title="Nova máquina" close={()=>setShowNew(false)}><form onSubmit={saveMachine} className="space-y-3"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome *"/><Input value={type} onChange={e=>setType(e.target.value)} placeholder="Tipo *"/><Input value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Identificação *"/><Button className="w-full bg-[#202321] text-white">Cadastrar</Button></form></Modal>}
{showLog&&<Modal title="Lançar horímetro" close={()=>setShowLog(false)}><form onSubmit={saveLog} className="space-y-3"><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={machineId} onChange={e=>setMachineId(e.target.value)} className="h-10 w-full border bg-white px-3 text-sm"><option value="">Selecione a máquina</option>{project.machines.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.identifier} · {m.name}</option>)}</select><select value={condition} onChange={e=>setCondition(e.target.value as LocalMachineCondition)} className="h-10 w-full border bg-white px-3 text-sm"><option>Trabalhando</option><option>Parado</option><option>Manutenção</option><option>Disponível</option></select><select value={frontId} onChange={e=>setFrontId(e.target.value)} disabled={condition!=="Trabalhando"} className="h-10 w-full border bg-white px-3 text-sm"><option value="">Frente</option>{project.fronts.map(f=><option key={f.id} value={f.id}>{f.code} · {f.name}</option>)}</select><Input value={operator} onChange={e=>setOperator(e.target.value)} placeholder="Operador"/><div className="grid grid-cols-2 gap-3"><Input type="number" step="0.1" value={start} onChange={e=>setStart(e.target.value)} placeholder="Horímetro inicial"/><Input type="number" step="0.1" value={end} onChange={e=>setEnd(e.target.value)} placeholder="Horímetro final"/></div><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Observação"/><Button className="w-full bg-[#202321] text-white">Salvar lançamento</Button></form></Modal>}</div></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/40 p-4" onMouseDown={close}><div className="w-full max-w-lg bg-[#ececea] p-5 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="mb-5 flex justify-between"><h2 className="text-2xl font-black uppercase">{title}</h2><Button variant="ghost" onClick={close}>Fechar</Button></div>{children}</div></div>}
