import { useMemo, useState } from "react";
import { useLocalProject, type LocalEventStatus, type LocalPriority } from "@/localStore";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Plus, Search, Trash2, X, ArrowUpRight } from "lucide-react";
import { toast } from "sonner";

const priorities: LocalPriority[] = ["Crítica", "Alta", "Média", "Baixa"];
const statuses: LocalEventStatus[] = ["Aberto", "Em tratamento", "Resolvido"];
const priorityClass = (p: LocalPriority) => p === "Crítica" ? "bg-[#c95a4a] text-white" : p === "Alta" ? "bg-[#d89b45] text-white" : "bg-[#dedfda] text-[#555b53]";

export default function OccurrencesPage() {
  const { project, addEvent, addAction, setEventStatus, replaceProject } = useLocalProject();
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<"Todos" | LocalEventStatus>("Todos");
  const [open, setOpen] = useState(false);
  const [actionOpen, setActionOpen] = useState<string | null>(null);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [impact, setImpact] = useState(""); const [decision, setDecision] = useState("");
  const [frontId, setFrontId] = useState(project.fronts[0]?.id ?? ""); const [priority, setPriority] = useState<LocalPriority>("Alta");
  const [actionTitle, setActionTitle] = useState(""); const [actionOwner, setActionOwner] = useState(""); const [actionDue, setActionDue] = useState(""); const [actionPriority, setActionPriority] = useState<LocalPriority>("Alta");
  const items = useMemo(() => project.events.filter(event => { const text = `${event.title} ${event.description} ${event.impact} ${event.decision} ${event.status}`.toLowerCase(); return text.includes(query.toLowerCase()) && (filter === "Todos" || event.status === filter); }), [project.events, query, filter]);
  const close = () => { setOpen(false); setTitle(""); setDescription(""); setImpact(""); setDecision(""); setPriority("Alta"); };
  const save = (e: React.FormEvent) => { e.preventDefault(); if (!title.trim() || !description.trim()) return toast.error("Informe o título e a descrição da ocorrência"); addEvent({ title: title.trim(), description: description.trim(), date: new Date().toISOString(), impact: impact.trim() || "Impacto ainda não informado", decision: decision.trim() || "Aguardando definição", priority, status: "Aberto", frontId: frontId || undefined }); close(); toast.success("Ocorrência registrada"); };
  const openAction = (eventId: string) => { const event = project.events.find(e => e.id === eventId); setActionOpen(eventId); setActionTitle(event ? `Resolver: ${event.title}` : ""); setActionOwner(""); setActionDue(""); setActionPriority(event?.priority ?? "Alta"); };
  const saveAction = (e: React.FormEvent) => { e.preventDefault(); if (!actionTitle.trim() || !actionOpen) return toast.error("Informe a ação"); const event = project.events.find(item => item.id === actionOpen); addAction({ title: actionTitle.trim(), owner: actionOwner.trim() || "Não informado", due: actionDue || "A definir", priority: actionPriority, done: false, eventId: actionOpen, frontId: event?.frontId }); setActionOpen(null); toast.success("Ação criada e vinculada à ocorrência"); };
  const remove = (id: string) => { if (!window.confirm("Excluir esta ocorrência? As ações vinculadas serão mantidas, mas ficarão sem a ocorrência.")) return; replaceProject({ ...project, events: project.events.filter(e => e.id !== id), actions: project.actions.map(a => a.eventId === id ? { ...a, eventId: undefined } : a) }); toast.success("Ocorrência excluída"); };
  return <div className="min-h-screen bg-[#ececea] px-4 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-5xl"><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#71756f]">Operação</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-black uppercase tracking-[-0.06em] sm:text-5xl">Ocorrências</h1><p className="mt-3 max-w-2xl text-sm text-[#70756e]">Problemas e desvios da obra, com tratamento e ações vinculadas.</p></div><Button onClick={() => setOpen(true)} className="bg-[#202321] text-white"><Plus className="mr-2 h-4 w-4"/>Nova ocorrência</Button></div>
    <div className="mt-7 flex flex-wrap gap-2">{(["Todos", ...statuses] as const).map(item => <Button key={item} variant={filter === item ? "default" : "outline"} className={filter === item ? "bg-[#202321] text-white" : ""} onClick={() => setFilter(item)}>{item}</Button>)}</div><div className="relative mt-5 max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-[#858a82]"/><Input value={query} onChange={e => setQuery(e.target.value)} className="bg-white pl-9" placeholder="Buscar ocorrência..."/></div>
    <div className="mt-6 space-y-3">{items.map(event => { const front = event.frontId ? project.fronts.find(f => f.id === event.frontId) : undefined; const linked = project.actions.filter(a => a.eventId === event.id); return <Card key={event.id} className="rounded-none border-0 bg-[#f6f6f3] shadow-[4px_4px_0_#d0d1cb]"><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#71756f]">{event.status}{front ? ` · ${front.code}` : ""}</p><h2 className="mt-1 font-black">{event.title}</h2></div><div className="flex items-center gap-2"><Badge className={`rounded-none ${priorityClass(event.priority)}`}>{event.priority}</Badge><Button size="icon" variant="ghost" onClick={() => remove(event.id)} className="text-[#b84f42]" aria-label="Excluir ocorrência"><Trash2 className="h-4 w-4"/></Button></div></div><p className="mt-3 text-sm leading-6">{event.description}</p><div className="mt-4 grid gap-2 text-xs text-[#70756e] sm:grid-cols-2"><p><b>Impacto:</b> {event.impact}</p><p><b>Tratamento:</b> {event.decision}</p></div><div className="mt-5 border-t border-black/10 pt-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#71756f]">Ações vinculadas · {linked.length}</p><Button size="sm" variant="outline" onClick={() => openAction(event.id)}><Plus className="mr-1 h-3.5 w-3.5"/>Criar ação</Button></div>{linked.length > 0 && <div className="mt-3 space-y-2">{linked.map(action => <div key={action.id} className="flex items-center gap-3 bg-white/70 p-3"><span className={`h-2.5 w-2.5 rounded-full ${action.done ? "bg-[#8da65a]" : "bg-[#d89b45]"}`}/><div className="min-w-0 flex-1"><p className={`text-xs font-semibold ${action.done ? "line-through text-[#858a82]" : ""}`}>{action.title}</p><p className="mt-1 text-[10px] text-[#858a82]">{action.owner} · {action.due === "A definir" ? "Sem prazo" : action.due}</p></div><Button size="icon" variant="ghost" onClick={() => setEventStatus(event.id, event.status)}><ArrowUpRight className="h-3.5 w-3.5"/></Button></div>)}</div>}</div><div className="mt-4 flex flex-wrap gap-2">{statuses.map(status => <Button key={status} size="sm" variant={event.status === status ? "default" : "outline"} className={event.status === status ? "bg-[#202321] text-white" : ""} onClick={() => { setEventStatus(event.id, status); toast.success(`Status atualizado para ${status}`); }}>{status}</Button>)}</div></CardContent></Card>})}{items.length === 0 && <Card className="rounded-none border-0 bg-[#f6f6f3]"><CardContent className="p-5 text-sm text-[#70756e]">Nenhuma ocorrência encontrada.</CardContent></Card>}</div>
    {open && <div className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-0 md:p-8"><div className="min-h-screen bg-[#f6f6f3] md:mx-auto md:min-h-0 md:max-w-2xl md:shadow-xl"><div className="sticky top-0 flex items-start justify-between border-b border-black/10 bg-[#f6f6f3] p-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#71756f]">Novo registro</p><h2 className="mt-1 text-2xl font-black uppercase">Nova ocorrência</h2></div><Button size="icon" variant="outline" onClick={close}><X className="h-4 w-4"/></Button></div><form onSubmit={save} className="grid gap-4 p-5 md:grid-cols-2"><Input autoFocus value={title} onChange={e=>setTitle(e.target.value)} className="bg-white md:col-span-2" placeholder="O que aconteceu?"/><Textarea value={description} onChange={e=>setDescription(e.target.value)} className="min-h-28 bg-white md:col-span-2" placeholder="Descreva a ocorrência e o contexto"/><Input value={impact} onChange={e=>setImpact(e.target.value)} className="bg-white" placeholder="Qual foi o impacto?"/><Input value={decision} onChange={e=>setDecision(e.target.value)} className="bg-white" placeholder="Tratamento inicial / decisão"/><select value={frontId} onChange={e=>setFrontId(e.target.value)} className="h-10 border border-black/10 bg-white px-3"><option value="">Sem frente vinculada</option>{project.fronts.map(f=><option key={f.id} value={f.id}>{f.code} · {f.name}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value as LocalPriority)} className="h-10 border border-black/10 bg-white px-3">{priorities.map(p=><option key={p}>{p}</option>)}</select><div className="flex justify-end gap-2 md:col-span-2"><Button type="button" variant="outline" onClick={close}>Cancelar</Button><Button type="submit" className="bg-[#202321] text-white">Salvar ocorrência</Button></div></form></div></div>}
    {actionOpen && <div className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-0 md:p-8"><div className="min-h-screen bg-[#f6f6f3] md:mx-auto md:min-h-0 md:max-w-2xl md:shadow-xl"><div className="sticky top-0 flex items-start justify-between border-b border-black/10 bg-[#f6f6f3] p-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#71756f]">Ocorrência vinculada</p><h2 className="mt-1 text-2xl font-black uppercase">Nova ação</h2></div><Button size="icon" variant="outline" onClick={() => setActionOpen(null)}><X className="h-4 w-4"/></Button></div><form onSubmit={saveAction} className="grid gap-4 p-5 md:grid-cols-2"><Input autoFocus value={actionTitle} onChange={e=>setActionTitle(e.target.value)} className="bg-white md:col-span-2" placeholder="O que precisa ser feito?"/><Input value={actionOwner} onChange={e=>setActionOwner(e.target.value)} className="bg-white" placeholder="Responsável"/><Input type="date" value={actionDue} onChange={e=>setActionDue(e.target.value)} className="bg-white"/><select value={actionPriority} onChange={e=>setActionPriority(e.target.value as LocalPriority)} className="h-10 border border-black/10 bg-white px-3">{priorities.map(p=><option key={p}>{p}</option>)}</select><div className="flex justify-end gap-2 md:col-span-2"><Button type="button" variant="outline" onClick={()=>setActionOpen(null)}>Cancelar</Button><Button type="submit" className="bg-[#202321] text-white">Criar ação</Button></div></form></div></div>}
  </div></div>;
}
