import { useMemo, useState, type FormEvent } from "react";
import { CircleHelp, Plus, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { useLocalProject, type LocalTeamAssignmentStatus } from "@/localStore";
import { getTeamDailyStatus } from "@/team";
const Kicker=({children}:{children:React.ReactNode})=><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#71756f]">{children}</p>;
const today=()=>new Date().toISOString().slice(0,10);
const statusStyle:Record<string,string>={Alocado:"bg-[#e5efd0] text-[#617a31]",Ocioso:"bg-[#f1dfc5] text-[#a56c1e]",Folga:"bg-[#dedfda] text-[#626760]",Outro:"bg-[#e4e8ed] text-[#52626f]","Sem alocação":"bg-[#f4d7d3] text-[#b84f42]"};
export default function TeamPage(){
 const {project,addTeamMember,upsertTeamAssignment}=useLocalProject(); const [showNew,setShowNew]=useState(false); const [showAssign,setShowAssign]=useState(false); const [date,setDate]=useState(today); const [name,setName]=useState(""); const [role,setRole]=useState(""); const [company,setCompany]=useState(""); const [memberId,setMemberId]=useState(""); const [frontId,setFrontId]=useState(""); const [status,setStatus]=useState<LocalTeamAssignmentStatus>("Alocado"); const [note,setNote]=useState("");
 const daily=useMemo(()=>getTeamDailyStatus(project,date),[project,date]);
 const saveMember=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!name.trim()||!role.trim()){toast.error("Informe nome e função.");return;}addTeamMember({name:name.trim(),role:role.trim(),company:company.trim()||"Não informado",active:true});setName("");setRole("");setCompany("");setShowNew(false);toast.success("Colaborador cadastrado");};
 const saveAssignment=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!memberId){toast.error("Selecione um colaborador.");return;}if(status==="Alocado"&&!frontId){toast.error("Selecione a frente.");return;}upsertTeamAssignment({date,memberId,frontId:status==="Alocado"?frontId:undefined,status,note:note.trim()});setNote("");setShowAssign(false);toast.success("Situação atualizada");};
 return <div className="min-h-screen bg-[#ececea] px-4 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><header className="border-b border-black/10 pb-6"><Kicker>Controle de pessoas</Kicker><h1 className="mt-3 text-5xl font-black uppercase tracking-[-0.08em]">Equipe</h1><p className="mt-3 max-w-2xl text-sm text-[#70756e]">Consulte a equipe e a situação de cada pessoa. Cadastros e lançamentos ficam disponíveis somente quando você solicitar.</p></header>
 <div className="mt-6 flex flex-wrap gap-3"><Button onClick={()=>setShowNew(true)} className="bg-[#202321] text-white"><Plus className="mr-2 h-4 w-4"/>Novo colaborador</Button><Button onClick={()=>setShowAssign(true)} variant="outline"><Plus className="mr-2 h-4 w-4"/>Lançar situação</Button><div className="ml-auto"><Input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-10 w-40 bg-white"/></div></div>
 <section className="mt-7"><div className="mb-3"><Kicker>Equipe ativa</Kicker><h2 className="mt-1 text-2xl font-black uppercase">Pessoas cadastradas</h2></div><div className="space-y-3">{daily.map(({member,assignment,state})=><Card key={member.id} className="rounded-none border-0 bg-[#f6f6f3] shadow-[4px_4px_0_#d0d1cb]"><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><Kicker>{member.role} · {member.company}</Kicker><h3 className="mt-1 text-base font-black uppercase">{member.name}</h3>{assignment?.note&&<p className="mt-2 text-xs text-[#70756e]">{assignment.note}</p>}</div><div className="flex items-center gap-2"><span className={`px-2 py-1 text-[10px] font-bold uppercase ${statusStyle[state]}`}>{state}</span>{assignment?.frontId&&<span className="text-xs font-semibold">{project.fronts.find(f=>f.id===assignment.frontId)?.code??"—"}</span>}</div></CardContent></Card>)}{daily.length===0&&<Card className="rounded-none border-0 bg-[#f6f6f3]"><CardContent className="p-6"><CircleHelp className="h-5 w-5 text-[#789249]"/><p className="mt-2 text-sm text-[#70756e]">Nenhum colaborador cadastrado. Use “Novo colaborador” para começar.</p></CardContent></Card>}</div></section>
 {showNew&&<Modal title="Novo colaborador" onClose={()=>setShowNew(false)}><form onSubmit={saveMember} className="space-y-3"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome completo *"/><Input value={role} onChange={e=>setRole(e.target.value)} placeholder="Função *"/><Input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Empresa ou equipe"/><Button type="submit" className="w-full bg-[#202321] text-white">Cadastrar colaborador</Button></form></Modal>}
 {showAssign&&<Modal title="Lançar situação" onClose={()=>setShowAssign(false)}><form onSubmit={saveAssignment} className="space-y-3"><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={memberId} onChange={e=>setMemberId(e.target.value)} className="h-10 w-full border bg-white px-3 text-sm"><option value="">Selecione o colaborador</option>{project.teamMembers.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value as LocalTeamAssignmentStatus)} className="h-10 w-full border bg-white px-3 text-sm"><option>Alocado</option><option>Ocioso</option><option>Folga</option><option>Outro</option></select><select value={frontId} onChange={e=>setFrontId(e.target.value)} disabled={status!=="Alocado"} className="h-10 w-full border bg-white px-3 text-sm"><option value="">Frente</option>{project.fronts.map(f=><option key={f.id} value={f.id}>{f.code} · {f.name}</option>)}</select><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Observação opcional"/><Button type="submit" className="w-full bg-[#202321] text-white">Salvar situação</Button></form></Modal>}
 </div></div>;
}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/40 p-4" onMouseDown={onClose}><div className="w-full max-w-lg bg-[#ececea] p-5 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black uppercase">{title}</h2><Button variant="ghost" onClick={onClose}>Fechar</Button></div>{children}</div></div>}
