import { and, eq, desc, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, users, projects, workFronts, actions, events, dailyLogs, attachments, services, productionEntries, decisions, notifications, costs, materials, machines, teamEntries } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; for (const field of ["name", "email", "loginMethod"] as const) { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } } values.lastSignedIn = user.lastSignedIn ?? new Date(); updateSet.lastSignedIn = values.lastSignedIn; if (user.role) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function listProjects(ownerId: number) { const db = await getDb(); if (!db) return []; return db.select().from(projects).where(eq(projects.ownerId, ownerId)).orderBy(desc(projects.updatedAt)); }
export async function createProject(input: { name: string; client?: string; location?: string; description?: string; ownerId: number }) { const db = await getDb(); if (!db) return undefined; return db.insert(projects).values({ ...input, status: "active" }); }
export async function createWorkFront(input: { projectId: number; name: string; code?: string; currentState?: string; nextStep?: string }) { const db = await getDb(); if (!db) return undefined; return db.insert(workFronts).values({ ...input, status: "planned", progress: "0" }); }
export async function createService(input: { frontId: number; name: string; unit: string; plannedQty: string }) { const db = await getDb(); if (!db) return undefined; return db.insert(services).values({ ...input, executedQty: "0", status: "planned" }); }
export async function getProjectForOwner(projectId: number, ownerId: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(projects).where(eq(projects.id, projectId)).limit(1); return result[0]?.ownerId === ownerId ? result[0] : undefined; }
export async function listFronts(projectId: number) { const db = await getDb(); if (!db) return []; return db.select().from(workFronts).where(eq(workFronts.projectId, projectId)).orderBy(desc(workFronts.updatedAt)); }
export async function listProjectServices(projectId: number) { const db = await getDb(); if (!db) return []; return db.select({ service: services, front: workFronts }).from(services).innerJoin(workFronts, eq(services.frontId, workFronts.id)).where(eq(workFronts.projectId, projectId)).orderBy(desc(services.createdAt)); }
export async function listProjectDecisions(projectId: number) { const db = await getDb(); if (!db) return []; return db.select().from(decisions).where(eq(decisions.projectId, projectId)).orderBy(desc(decisions.createdAt)); }
export async function listProjectNotifications(projectId: number, recipientId: number) { const db = await getDb(); if (!db) return []; return db.select().from(notifications).where(and(eq(notifications.projectId, projectId), eq(notifications.recipientId, recipientId))).orderBy(desc(notifications.createdAt)); }
export async function listProjectActions(projectId: number) { const db = await getDb(); if (!db) return []; return db.select().from(actions).where(eq(actions.projectId, projectId)).orderBy(desc(actions.createdAt)); }
export async function listProjectEvents(projectId: number) { const db = await getDb(); if (!db) return []; return db.select().from(events).where(eq(events.projectId, projectId)).orderBy(desc(events.createdAt)); }
export async function listDailyLogs(projectId: number) { const db = await getDb(); if (!db) return []; return db.select().from(dailyLogs).where(eq(dailyLogs.projectId, projectId)).orderBy(desc(dailyLogs.logDate)); }
export async function createDailyLog(input: { projectId: number; authorId: number; logDate: Date; summary?: string; weather?: string; workforce?: number; workedHours?: string }) { const db = await getDb(); if (!db) return undefined; const result = await db.insert(dailyLogs).values(input); return result[0]; }
export async function createEvent(input: { projectId: number; frontId?: number; serviceId?: number; dailyLogId?: number; title: string; description?: string; category: string; severity: "low" | "medium" | "high" | "critical"; impact?: string }) { const db = await getDb(); if (!db) return undefined; return db.insert(events).values(input); }
export async function createAction(input: { projectId: number; eventId?: number; title: string; ownerName?: string; dueAt?: Date; priority: "low" | "medium" | "high" | "critical" }) { const db = await getDb(); if (!db) return undefined; return db.insert(actions).values(input); }
export async function createAttachment(input: { projectId: number; dailyLogId?: number; eventId?: number; actionId?: number; fileName: string; fileKey: string; fileUrl: string; mimeType?: string }) { const db = await getDb(); if (!db) return undefined; return db.insert(attachments).values(input); }
export async function createProductionEntry(input: { projectId: number; frontId: number; serviceId: number; dailyLogId?: number; quantity: string; unit: string; entryDate: Date }) { const db = await getDb(); if (!db) return undefined; const linked = await db.select({ serviceId: services.id, frontId: workFronts.id }).from(services).innerJoin(workFronts, eq(services.frontId, workFronts.id)).where(and(eq(services.id, input.serviceId), eq(workFronts.id, input.frontId), eq(workFronts.projectId, input.projectId))).limit(1); if (!linked.length) throw new Error("Serviço não pertence à obra informada"); await db.insert(productionEntries).values(input); await db.update(services).set({ executedQty: sql`${services.executedQty} + ${input.quantity}`, status: "in_progress" }).where(eq(services.id, input.serviceId)); const frontServices = await db.select().from(services).where(eq(services.frontId, input.frontId)); const planned = frontServices.reduce((sum, service) => sum + Number(service.plannedQty || 0), 0); const executed = frontServices.reduce((sum, service) => sum + Number(service.executedQty || 0), 0) + Number(input.quantity); const progress = planned > 0 ? Math.min(100, (executed / planned) * 100).toFixed(2) : "0"; await db.update(workFronts).set({ progress }).where(eq(workFronts.id, input.frontId)); return { success: true as const, progress }; }
export async function updateActionStatus(projectId: number, actionId: number, status: "open" | "in_progress" | "done" | "overdue") { const db = await getDb(); if (!db) return undefined; await db.update(actions).set({ status, completedAt: status === "done" ? new Date() : null }).where(and(eq(actions.id, actionId), eq(actions.projectId, projectId))); return { success: true as const }; }

export async function createCost(input: { projectId: number; frontId?: number; description: string; category?: string; value: string; occurredAt?: Date; source?: string }) { const db = await getDb(); if (!db) return undefined; return db.insert(costs).values(input); }
export async function createMaterial(input: { projectId: number; frontId?: number; description: string; quantity?: string; unit?: string; supplier?: string; occurredAt?: Date; source?: string }) { const db = await getDb(); if (!db) return undefined; return db.insert(materials).values(input); }
export async function createMachine(input: { projectId: number; frontId?: number; equipment: string; event?: string; description?: string; durationHours?: string; occurredAt?: Date; source?: string }) { const db = await getDb(); if (!db) return undefined; return db.insert(machines).values(input); }
export async function createTeamEntry(input: { projectId: number; frontId?: number; personName?: string; role?: string; quantity?: number; description?: string; occurredAt?: Date; source?: string }) { const db = await getDb(); if (!db) return undefined; return db.insert(teamEntries).values(input); }
export async function listProjectCosts(projectId: number) { const db = await getDb(); if (!db) return []; return db.select().from(costs).where(eq(costs.projectId, projectId)).orderBy(desc(costs.occurredAt)); }
export async function listProjectMaterials(projectId: number) { const db = await getDb(); if (!db) return []; return db.select().from(materials).where(eq(materials.projectId, projectId)).orderBy(desc(materials.occurredAt)); }
export async function listProjectMachines(projectId: number) { const db = await getDb(); if (!db) return []; return db.select().from(machines).where(eq(machines.projectId, projectId)).orderBy(desc(machines.occurredAt)); }
export async function listProjectTeam(projectId: number) { const db = await getDb(); if (!db) return []; return db.select().from(teamEntries).where(eq(teamEntries.projectId, projectId)).orderBy(desc(teamEntries.occurredAt)); }
